<!-- GENERATED by cg specgen from spec/ kvx — DO NOT EDIT. Edit the .kvx source and regenerate. -->

# Requirements

Redesign the standalone Keith web application and terminal client around one promise: Keith is a personal intelligence and dependable right hand that an ordinary person can use without learning agent infrastructure. The web application presents conversations, current work, useful outputs, and the parts of the user's world Keith is trusted to remember. The terminal client follows the Codex interaction model: native terminal scrollback, a quiet conversation canvas, a compact bottom composer, truthful live activity, and temporary overlays instead of a permanent operator dashboard. Both clients remain projections over AgentConnection and the Rust reducer; neither invents activity or creates a second agent runtime.

## Requirement 1: Standalone consumer product boundary

**User Story:** As a person using Keith, I want capable help expressed in familiar language, so that I never have to operate agent infrastructure.

### Acceptance Criteria

1. THIS feature SHALL modify only the standalone Keith clients and shared Keith client projections; it SHALL NOT modify or imitate the Neo/Centra unified cloud interface.
2. THE default web experience SHALL describe outcomes, conversations, current work, saved context, approvals, and completed results in ordinary language and SHALL NOT expose queues, kernels, workers, generations, raw tool-call identifiers, protocol sequences, or internal surface names.
3. ADVANCED diagnostics and provider configuration SHALL remain available behind an explicitly opened settings or diagnostics route and SHALL never occupy the primary navigation or conversation canvas.
4. EMPTY states SHALL explain what Keith can do next with a concrete action; they SHALL NOT show placeholder panels, raw counts, or implementation notes.
5. PRODUCT copy SHALL present Keith as a dependable personal intelligence and companion without claiming consciousness, background thought, fabricated typing, or work not represented by authoritative runtime state.

## Requirement 2: One authoritative client state and consumer projection vocabulary

**User Story:** As a user switching between web and terminal, I want the same truthful Keith state everywhere, so that presentation never becomes a second runtime.

### Acceptance Criteria

1. AgentConnection snapshots, ordered events, command results, terminal frames, and the Rust ProjectionReducer SHALL remain the sole authority for conversation and activity state.
2. A shared consumer projection SHALL group low-level runtime facts into Conversation, Work, NeedsYou, Completed, Upcoming, SavedContext, and Outputs without discarding exact source identifiers needed for commands.
3. THE projection SHALL expose calm user-facing presence copy derived only from authoritative PresenceProjection and terminal state; local HTTP requests, timers, animation, and command counts SHALL NOT be presented as Keith working.
4. THE Solid application SHALL consume read-only snapshots from a Rust/WASM adapter and SHALL NOT define an independent message reducer, tool executor, model provider, or optimistic terminal state.
5. @tanstack/solid-query MAY cache bounded non-streaming catalog resources and @tanstack/solid-virtual MAY window rendered history; @tanstack/ai-solid SHALL NOT own Keith messages, execute client tools, or bypass AgentConnection.
6. REDUCER tests SHALL cover exact consumer grouping, correction after replacement snapshots, stream gaps, terminal failures, zero activity, and absence of fabricated work.

## Requirement 3: Codex-class conversation-first terminal structure

**User Story:** As a terminal user, I want Keith to feel as focused and reliable as Codex, so that the terminal disappears behind the conversation.

### Acceptance Criteria

1. THE default TUI SHALL contain a quiet conversation transcript, a compact live activity region when authoritative activity exists, a bottom composer, and a one-line status/hint row; it SHALL NOT contain a permanent navigation sidebar or a grid of subsystem panels.
2. SETTLED messages SHALL be promoted into native terminal scrollback in inline viewport mode while only the uncommitted streaming tail, composer, transient notice, and open overlay remain mutable.
3. USER, Keith, tool/activity, warning, and terminal-result entries SHALL have distinct restrained typographic treatment, safe wrapping, code-preserving indentation, and terminal-control neutralization.
4. SESSION selection, command help, model selection, approvals, memory lookup, work details, and diagnostics SHALL open as temporary searchable overlays or slash-command results and SHALL return to the conversation with Escape.
5. THE composer SHALL support Unicode, bracketed paste, multiple lines, external editor handoff, cursor-safe edits, Enter to send, Alt-Enter for a newline, steering, cancellation, retry, branch, and resume without losing draft text.
6. NARROW terminals SHALL preserve the transcript and composer by reducing secondary hints; they SHALL never replace the conversation with a resize instruction.

## Requirement 4: Continuous terminal subscription, recovery, and truth

**User Story:** As a user leaving Keith open, I want events to arrive without issuing another command, so that background completion and failure are never missed.

### Acceptance Criteria

1. THE TUI connection layer SHALL receive ordered events continuously while idle and while commands are in flight, using bounded channels and one negotiated client identity.
2. COMMAND results SHALL correlate by command ID without preventing unrelated streamed events, terminal frames, acknowledgements, cancellation, or reconnect.
3. RECONNECT SHALL use the latest reducer generation and sequence cursor and SHALL request replacement snapshot state on a gap without replaying an effect whose outcome is unknown.
4. THE UI SHALL distinguish connecting, reconnecting, caught up, waiting for Keith, paused for the user, interrupted, incomplete, failed, cancelled, and completed using authoritative state only.
5. PROCESS tests SHALL prove an event delivered during command-idle time appears without another outbound command, cancel stays responsive, reconnect resumes exactly, and terminal restoration occurs after error, signal, and external-editor paths.

## Requirement 5: First-class personal-intelligence web architecture

**User Story:** As an everyday user, I want one beautiful place for Keith and my ongoing life, so that deep capability feels obvious rather than technical.

### Acceptance Criteria

1. THE standalone web client SHALL use SolidJS for rendering and keep the authenticated Rust server, exact-origin and CSRF mutation boundary, write-only credential path, WebSocket subscription, and Rust/WASM protocol authority.
2. PRIMARY navigation SHALL contain at most Home, Conversation, Work, Your World, and a compact Settings entry; the persistent conversation SHALL remain mounted while other destinations open.
3. HOME SHALL provide a personal brief composed only from authoritative current focus, needs-you items, completed results, upcoming schedules/commitments, and a direct message action.
4. WORK SHALL unify goals, plans, actions, children, tools, waits, schedules, commitments, confirmations, and deliveries into outcome-oriented Active, Needs you, Upcoming, and Completed groupings.
5. YOUR WORLD SHALL present user-visible saved context, knowledge, routines, preferences, and memory changes with inspect, correct, forget, and search affordances where the protocol supports them.
6. OUTPUTS and artifacts SHALL appear in the conversation and relevant work item with clear open, download, and provenance affordances instead of a disconnected technical panel.

## Requirement 6: OpenAI Apps SDK UI token and CSS foundation

**User Story:** As a user, I want Keith to feel composed, premium, and consistent, so that every state earns trust.

### Acceptance Criteria

1. THE web bundle SHALL import @openai/apps-sdk-ui/css as the authoritative source for base reset, color, typography, radius, focus, elevation, motion, and component semantic tokens.
2. KEITH CSS SHALL use Apps SDK semantic variables or explicit Keith aliases of those variables for every color, font, radius, focus, surface, and motion decision; raw product color literals SHALL be prohibited outside the token adapter.
3. THE interface SHALL use background-color contrast, spacing, type, and restrained elevation for hierarchy; it SHALL render no decorative border strokes, glow, purple gradient, or emoji status.
4. LIGHT, dark, high-contrast, reduced-motion, text zoom, and forced-colors modes SHALL retain readable hierarchy and visible focus without depending on color alone.
5. ICONS SHALL be accessible, restrained, and sourced through an Apps-SDK-compatible Solid adapter; an icon SHALL never be the sole label for an unfamiliar or consequential action.
6. A build-time style audit SHALL verify the Apps SDK CSS import, token-only Keith styles, forbidden visual treatments, and absence of inline style attributes in product components.

## Requirement 7: Conversation, activity, approvals, and recovery on the web

**User Story:** As a user delegating real work, I want conversation to remain the center while Keith acts, so that I understand what happened without watching machinery.

### Acceptance Criteria

1. THE conversation SHALL render keyed incremental messages, preserve reader scroll position, follow the live tail only when already near it, expose a new-activity affordance otherwise, and window long histories without clearing and rebuilding the transcript.
2. THE renderer SHALL safely present paragraphs, lists, links, code, tool/activity summaries, warnings, artifacts, incomplete output, and terminal results without unsafe HTML or terminal-control effects.
3. THE composer SHALL support Enter to send, Shift-Enter for newline, paste, draft preservation across navigation/reconnect, disabled explanation when no session is selected, steering, stop, retry, branch, and resume.
4. CONSEQUENTIAL confirmations SHALL use natural-language summaries, scope, consequence, and Allow once or Deny actions; raw confirmation identifiers SHALL remain internal.
5. NETWORK, protocol, and runtime failures SHALL retain the draft and committed transcript, state what is known, offer only safe recovery actions, and never tell the user to blindly retry an effect with unknown outcome.
6. THE web client SHALL not infer success from HTTP acceptance; completion, failure, artifacts, and delivery state SHALL come from authoritative snapshots, terminal frames, and events.

## Requirement 8: Responsive, accessible, and durable web use

**User Story:** As a user on any device or with assistive technology, I want the full Keith relationship to remain usable, so that capability does not depend on a desktop layout.

### Acceptance Criteria

1. PHONE, tablet, laptop, wide desktop, installed desktop shell, and 200 percent text zoom SHALL preserve session switching, navigation, conversation, composer, approvals, and work inspection.
2. MOBILE SHALL use a real dismissible navigation/session sheet and SHALL NOT hide the only session picker or compress every destination into a horizontal strip.
3. CRITICAL paths SHALL meet WCAG 2.2 AA for keyboard order, visible focus, names/roles/values, landmarks, announcements, target size, contrast, zoom, and motion.
4. CONNECTION and presence announcements SHALL be rate-limited and meaningful; streaming text SHALL not repeatedly reread the entire conversation to screen readers.
5. THE browser SHALL keep credentials and bearer values out of URLs, storage, rendered markup, diagnostics, and bundles and SHALL retain the existing origin, CSRF, authentication, rate, and profile-scope defenses.
6. REAL Chromium journeys SHALL cover sign-in, first use, session switch, send, stream, navigate without conversation remount, approval, work inspection, memory search, refresh, disconnect/reconnect, narrow mobile, keyboard-only use, reduced motion, and secret scans.

## Requirement 9: Cross-client quality, packaging, and parity gate

**User Story:** As the owner shipping Keith, I want both clients qualified as products, so that a polished screenshot cannot hide a broken runtime path.

### Acceptance Criteria

1. THE TUI and web client SHALL expose equivalent core commands through consumer-appropriate interaction while keeping diagnostics and configuration presentation platform-specific.
2. A parity matrix SHALL map Submit, Steer, Stop, Retry, Branch, Resume, Sessions, Model, Confirmation, Goals, Children, Schedules, Memory, Export, and Background controls to real AgentConnection commands in both clients.
3. TERMINAL qualification SHALL cover truecolor, 256-color, no-color, high-contrast, narrow widths, Unicode, paste, long history, continuous idle events, reconnect, SSH-like TERM values, tmux/screen-like TERM values, and restoration.
4. WEB qualification SHALL use production-built Solid assets and Rust/WASM output served by the real authenticated Rust server, not source-string assertions or a separate prototype route.
5. THE desktop and release assemblers SHALL package the same production web assets and SHALL fail when generated JS, CSS, WASM, manifests, or lockfiles are stale or missing.
6. THE feature SHALL complete only after focused tests, workspace formatting and linting, web typecheck/build, real browser journeys, packaging checks, Codify graph/touch checks, and the full declared client gate pass.

