/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_browserprojection_free: (a: number, b: number) => void;
export const browserprojection_apply_wire_message: (a: number, b: number, c: number) => [number, number, number, number];
export const browserprojection_attach_session: (a: number, b: number, c: number) => [number, number, number, number];
export const browserprojection_branch: (a: number, b: number, c: number) => [number, number, number, number];
export const browserprojection_cancel: (a: number, b: number, c: number) => [number, number, number, number];
export const browserprojection_create_child: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const browserprojection_create_goal: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const browserprojection_create_schedule: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: bigint) => [number, number, number, number];
export const browserprojection_create_session: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const browserprojection_current_view: (a: number) => [number, number, number, number];
export const browserprojection_export_session: (a: number, b: number, c: number) => [number, number, number, number];
export const browserprojection_list_sessions: (a: number, b: number, c: number) => [number, number, number, number];
export const browserprojection_new: () => number;
export const browserprojection_query_memory: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const browserprojection_resolve_confirmation: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const browserprojection_resume: (a: number, b: number, c: number) => [number, number, number, number];
export const browserprojection_retry: (a: number, b: number, c: number) => [number, number, number, number];
export const browserprojection_select_model: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const browserprojection_set_background: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const browserprojection_steer: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const browserprojection_submit_prompt: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
