<!-- GENERATED by cg specgen from spec/ kvx — DO NOT EDIT. Edit the .kvx source and regenerate. -->

A shared platform-contracts crate defines external principals, capability grants, action risk, approvals, audit envelopes, trace bundles, connected accounts, computer sessions, and exclusive control leases. Nine conflict-free worker streams build Meta-Harness, channel families, ACP, plugins, Composio, CUA, and teaching against that boundary while an integration owner alone edits central daemon, protocol, state, and application mounting surfaces. Meta-Harness diagnoses harness-caused failures from complete execution traces, proposes bounded shadow candidates, ranks them on a Pareto frontier, and promotes only through the existing signed self-evolution, canary, observation, and reversal path. Channel adapters normalize every platform through the durable gateway. ACP remains a client-to-agent protocol while MCP and plugins remain agent-to-tool protocols. Keith Computer is an isolated Linux workstation with semantic and visual observation, authenticated screen streaming, exclusive user-or-Keith input control, and a demonstration recorder that compiles synchronized screen, input, DOM, accessibility, and narration evidence into editable replayable TaskRecipes.

# Keith Everywhere — Technical Design

## 1. Outcome

Keith Everywhere is one expansion of the existing Keith product, not five adjacent products. The same daemon, profile, credentials, durable sessions, action inbox, approvals, audit records, event stream, resource governor, and client connection remain authoritative while five new capabilities are added:

1. Meta-Harness repairs harness-caused failures through bounded candidate search and held-out evidence.
2. Channel reach expands beyond Discord to Slack, Telegram, WhatsApp Cloud, Microsoft Teams, Google Chat, email, and Matrix.
3. ACP makes Keith available to compatible clients and editors without adding another agent loop.
4. Typed WASI plugins and Composio sessions connect external applications under Keith authority.
5. Keith Computer provides an isolated visible workstation with exclusive co-control and teach-by-demonstration.

The release succeeds only when these capabilities work together in one durable user journey.

## 2. Execution model

The specification runs in Codify parallel mode with ten logical owners. One integration captain owns every high-conflict central surface. Nine worker owners receive disjoint first-wave paths. The installed control plane may execute fewer than ten operating-system processes simultaneously, but task ownership, leases, scopes, evidence, and handoffs retain the ten-agent plan.

Agent ownership:

| Agent | Primary ownership | Central-file rule |
|---|---|---|
| 1 | Platform contracts, integration, final release | Sole editor of shared daemon, protocol, state registration, main web mounting, and release aggregation |
| 2 | Meta-Harness | Owns meta-harness crate; touches self-evolution only in its later integration task |
| 3 | Channel contract, gateway, Slack | Owns channel-core changes and Slack files |
| 4 | Telegram and WhatsApp | Owns only its adapter and test files |
| 5 | Teams, Google Chat, email, Matrix | Owns only its adapter and test files |
| 6 | ACP | Owns ACP crate and agent binary |
| 7 | Plugin ABI and host | Owns plugin SDK and host in dependency order |
| 8 | Composio and Apps | Owns connector crate and isolated Apps components |
| 9 | CUA runtime and co-control | Owns CUA crate, runner, and isolated ComputerStage components |
| 10 | Demonstrations and recipes | Owns task-recipe crate and isolated teaching components |

Only Agent 1 mounts isolated UI components into KeithApp, registers shared persisted collections, changes central protocol enums, or resolves cross-stream API differences. New crates are discovered by the workspace wildcard and do not require parallel edits to the root manifest.

## 3. Shared platform contracts

The platform-contracts crate is intentionally small, stable, and dependency-light. It defines integration vocabulary rather than implementing subsystem behavior.

Core identities:

- ExternalPrincipal identifies the authenticated human, service account, channel sender, ACP client, plugin publisher, connector user, or computer observer.
- ConnectedAccountRef identifies a profile-owned application or channel account without carrying credentials.
- ComputerSessionId, DemonstrationId, RecipeId, HarnessExperimentId, and HarnessCandidateId use opaque stable values.
- AuditCorrelation ties a user intent through SessionAction, tool or computer execution, delivery, recording, evaluation, and result.

Authority:

- CapabilityGrant names the allowed operation and bounded resource or target scope.
- ActionRisk classifies read, reversible local write, external communication, deletion, purchase, account change, credential change, and irreversible input.
- ApprovalEnvelope records the exact target and observed preconditions approved by a human.
- ControlLease represents exclusive input authority for KeithControl, UserControl, or Paused.
- Authority composition always chooses the intersection of all applicable grants and the strongest denial or approval requirement.

Evidence:

- ExecutionTraceBundle contains bounded structured events and references to separately stored artifacts.
- Trace data includes observed inputs and results but excludes hidden reasoning, reusable secrets, private credential material, and unbounded platform payloads.
- Every event carries occurrence time, source identity, session and profile, sequence, action or correlation id, lifecycle state, and redaction status.

## 4. Meta-Harness architecture

Meta-Harness is an outer optimization loop around Keith's existing self-evolution transaction. It does not modify model weights and never edits the live checkout during search.

### 4.1 Diagnostic flow

1. A failed, corrected, excessively retried, prematurely completed, or explicitly reported task becomes a diagnostic candidate.
2. Trace assembly selects complete relevant runtime evidence, harness code, configuration source, tool schemas, context construction decisions, completion decisions, and user corrections.
3. Attribution distinguishes model, environment, external service, ambiguity, user input, and harness causes.
4. A harness diagnosis names one causal component, reproduction, target metric, baseline, threshold, cost ceiling, and revert threshold.
5. Duplicate or recently failed diagnoses are suppressed.

Harness causes include context selection, tool visibility or schema, planner routing, retry policy, recovery, memory selection, compaction, channel or ACP translation, permission dead ends, completion detection, and finalization.

### 4.2 Candidate search

The proposer receives a read-only filesystem view containing selected prior candidate code, diffs, scores, and raw traces. The view is bounded and omits evaluator implementation, held-out data, credentials, personal-memory authority, approval policy, release verification, rollback, and guard state.

Each admitted experiment includes the unchanged baseline plus several candidate shadow trees. Candidate edits must remain inside an allowlisted source surface and resource budget. Every candidate records its full lineage and terminal disposition.

### 4.3 Evaluation

Search, validation, and held-out sets are versioned separately. The proposer sees search feedback but never held-out inputs, outputs, or scores. Evaluation measures task success, truthful completion, safety, correction adherence, cost, latency, retry count, and resource use. A Pareto frontier preserves non-dominated candidates and prevents one opaque scalar from hiding regressions.

A candidate reaches promotion only through the existing real build, signed artifact, canary worker, observation window, known-good pin, and reversal path. Advisory and shadow modes precede autonomous mode.

## 5. Channel architecture

All channel processes remain thin adapters around channel-core, channel-gateway, AgentConnection, and the durable outbox.

### 5.1 Normalized event

Normalized events carry platform, external account, conversation, thread, sender, message, reply target, occurrence time, text, rich content, attachments, mentions, commands, reactions, edit or deletion state, receipts, and platform metadata. Platform payloads remain bounded and untrusted.

### 5.2 Capabilities

Each adapter declares support for replies, threads, mentions, commands, edits, deletion, reactions, images, files, voice, rich blocks, typing, receipts, cancellation, steering, idempotent send, webhook, polling, socket, and reconnect. The client uses this declaration to hide or disable unsupported controls and to label limitations honestly.

### 5.3 Platform groups

- Discord remains the first adapter and is upgraded to the versioned contract.
- Slack supports socket and webhook operation, threads, files, reactions, edits, and typing where available.
- Telegram supports webhooks and polling fallback, topics, commands, files, voice, edits, and typing.
- WhatsApp Cloud supports verified webhooks, text, media, replies, templates, delivery statuses, and token rotation.
- Teams and Google Chat support their platform event, conversation, thread, mention, file, and card capabilities.
- Email supports profile-scoped receive and send, thread reconstruction, attachments, idempotent intent, and possible-duplicate disclosure.
- Matrix supports sync cursors, rooms, threads, replies, edits, reactions, media, reconnect, and an explicit encryption capability state.

No adapter counts as supported until its credentialed matrix passes. Missing vendor approval is a named external blocker, not a successful fixture.

## 6. ACP architecture

ACP is a client-to-Keith boundary. MCP is a Keith-to-tool boundary. They remain distinct even when an ACP client supplies MCP server configurations.

The ACP agent binary connects to the same AgentConnection used by Web and TUI. It implements stable protocol v1 first. It maps initialization, session creation, load, resume, fork, prompt, cancel, attachments, and content blocks to durable Keith operations. Keith events project back as streamed content, plans, safe thought summaries, tool state, terminal output, diffs, usage, failures, and final state.

Client-provided filesystem, terminal, permission, and MCP capabilities become scoped tools. They cannot expand the profile workspace, credential, process, or network boundary. Stdio is the mandatory local transport; authenticated HTTP or SSE and WebSocket provide managed deployment. Draft v2 has separate handlers and feature gates with no silent conversion or downgrade.

## 7. Plugin architecture

The existing plugin manifest and lifecycle become a typed WASI component platform.

The WIT boundary includes:

- Lifecycle activate, health, migrate, deactivate.
- Tool and command descriptors.
- Versioned request and response payloads.
- Output chunks and terminal response.
- Cancellation.
- Bounded HTTP, named credential, profile-local storage, event, artifact, clock, and safe-log host calls.

The plugin never receives an ambient directory, network, environment, process, or credential namespace. Manifests describe publisher, digest, signature, API compatibility, hooks, tools, schemas, grants, limits, and migration. Installation and update verify publisher continuity and show grant changes before approval. Quarantine and safe mode protect daemon startup.

## 8. Composio architecture

Composio is the first broad external-application provider, connected through the existing MCP manager.

Each Keith profile maps to one stable provider identity. A resumable provider session exposes a hosted MCP URL and headers retained only in the credential layer. Sessions restrict toolkits and tools; they never enable the provider catalog wholesale. Tool discovery remains bounded by schema and context budgets.

Connected accounts expose safe identity, toolkit, scopes, auth configuration, status, selection precedence, and health. Several accounts for one toolkit require explicit or deterministic profile-owned selection. Keith performs its own approval, audit, cancellation, timeout, result limit, and redaction around every hosted MCP call. Provider remote compute is disabled unless separately and explicitly authorized.

## 9. Keith Computer architecture

Keith Computer is an isolated workstation service rather than a browser status card.

### 9.1 Runtime

Each computer session owns an isolated Linux environment, headed Chromium, profile directory, workspace volume, clipboard, process namespace, network policy, resource limits, and lifecycle. Persistent mode retains authorized state. Ephemeral mode destroys it on termination. Snapshot and reset are explicit operations.

### 9.2 Observation and action

ComputerObservation combines screenshot, DOM, accessibility, focused window, URL, viewport, cursor, dialogs, downloads, and recent actions. ComputerAction supports mouse, keyboard, text, scroll, drag, clipboard, files, tabs, windows, navigation, and waits.

Semantic targets are preferred. A coordinate target includes the source frame id and becomes invalid when geometry changes. Every meaningful action produces a new observation and progress decision. Consequential actions require target-specific approval immediately before execution.

### 9.3 Streaming and control

The browser receives a short-lived authenticated screen-stream negotiation, never a reusable backend VNC or debugging address. The control service grants exactly one input lease. User takeover cancels queued and in-flight Keith input before granting UserControl. Keith requests control and never steals it. Paused allows observation without input.

## 10. Teaching architecture

A demonstration is more than video. The recorder synchronizes screen frames, raw pointer and keyboard events, semantic targets, URL, window, application, clipboard and file actions, timing, pauses, narration, and control transitions.

Sensitive values are detected before persistence and replaced with named parameters or credential references. The compiler transforms the timeline into a TaskRecipe containing inputs, preconditions, semantic steps, visual fallbacks, expected observations, checkpoints, approvals, recovery branches, and completion conditions.

The user can edit targets and parameters, remove steps, add confirmations, resume from a checkpoint, and correct a failed replay. Recipes replay in a shadow or explicit test context before publication as a skill. Recording media, recipes, derived indexes, and published skills retain linked versions and exact deletion scopes.

## 11. Client integration

Keith's existing information architecture remains primary.

- Keith Computer evolves from a work-status panel into the live authenticated screen while retaining current tool, goal, child, wait, terminal, and final projections.
- Channels manages accounts, capabilities, routes, health, tests, pause, and removal.
- Apps manages connected accounts, scopes, allowed tools, health, approval, invocation, and revocation.
- Plugins manages packages, publishers, versions, grants, tools, health, updates, rollback, and uninstall.
- ACP shows local and managed connection health and active sessions without presenting ACP as another agent identity.
- Teach Task lives inside Keith Computer and produces Recipes.
- Harness Repairs shows diagnoses, candidates, evidence, comparisons, diffs, promotion, observation, and reversal.

The TUI and protocol expose the same authoritative operations. Clients never implement adapter routing, approval, recipe compilation, candidate evaluation, or computer control arbitration.

## 12. Persistence and recovery

Every new durable object uses explicit state transitions and stable identity. On restart:

- Channel cursors and deliveries reconcile without blind external replay.
- ACP sessions reconnect to durable Keith sessions without duplicate prompts.
- Plugin invocations resolve to completed, cancelled, failed, or interrupted.
- Composio sessions resume or require reauthorization without account substitution.
- Computer sessions resume, restore, or become explicitly unavailable; stale input leases expire.
- Demonstrations resume only when capture integrity is provable; otherwise they close interrupted.
- Recipe replays resume from durable checkpoints or stop before non-repeatable actions.
- Harness experiments reclaim shadows and canaries while preserving candidates and evidence.

One failed subsystem never prevents ordinary daemon startup, conversation, cancellation, reversal, or data deletion.

## 13. Security model

External channel content, ACP clients, plugins, MCP servers, Composio results, websites, computer applications, recordings, recipes, traces, and candidate patches are mutually untrusted.

No input from one surface can approve another surface, widen a grant, select another profile, expose a credential, install a plugin, connect an account, acquire computer control, enable self-evolution, alter an evaluator, or promote a candidate.

High-priority adversarial cases:

- Forged and replayed webhooks.
- JSON-RPC protocol confusion and malformed batches.
- WASI traversal, resource exhaustion, network and credential escape.
- OAuth account substitution and callback confusion.
- SSRF and local-network access through tools, plugins, connectors, or computer navigation.
- Stream token theft and unauthorized observers.
- Stale screenshot coordinate injection and simultaneous input.
- Sensitive value leakage through frames, recordings, narration, recipes, logs, or traces.
- Evaluator mutation, held-out leakage, reward hacking, and protected-surface edits.
- Cross-profile routing, storage, credential, session, computer, recipe, candidate, and audit access.

## 14. Forty-eight-hour execution schedule

Hours 0–2:

- Activate this feature and parallel mode.
- Build and qualify platform contracts.
- Publish task-linked ownership and integration decisions.
- Make the first conflict-free wave eligible.

Hours 2–10:

- Nine worker streams implement their first vertical contract and focused proof.
- Agent 1 maintains integration APIs and reviews deltas without taking worker files.

Hours 10–20:

- Meta-Harness diagnoses and evaluates its first candidates.
- First channel round trips, ACP session, typed plugin invocation, Composio discovery, live computer action, and demonstration record work.

Hours 20–30:

- Complete channel breadth, ACP capabilities and transports, plugin lifecycle, Apps UI, screen co-control, recipe replay, and harness promotion integration.

Hours 30–40:

- Agent 1 wires central daemon, protocol, persistence, runtime, Web, and TUI surfaces.
- Integrated journey runs and exposes cross-stream defects.

Hours 40–46:

- Credentialed, process, browser, interoperability, security, restart, cancellation, revocation, takeover, recording, evaluation, promotion, and reversal qualification.

Hours 46–48:

- Run the combined release gate, Codify review, strict guard, check, test impact, task traces, snapshots, qualification, and honest final handoff.

## 15. Codify lifecycle

Every task follows the same evidence loop:

1. Claim a conflict-free eligible task with a named agent and bounded lease.
2. Open the revisioned work packet and use graph context, survey, impact, why, and recall before editing.
3. Start the task and implement only its declared acceptance criteria and paths.
4. Update progress with novel evidence and record durable decisions or constraints.
5. Run test impact, review, guard, and the focused verification command.
6. Snapshot with task attribution.
7. In parallel Prod semantics, mark source-complete work implemented only when graph evidence exists; mark done only when executable qualification passes.
8. Trace task to symbols, touched files, commits, memories, and evidence.
9. Hand off exact done, next, and blocked state before changing owner or ending a session.

No process exit, status declaration, fixture-only green result, or generated Markdown is completion evidence.

## 16. Release proof

The primary journey begins with a real non-Discord channel message. Keith resumes the same durable session through Web or ACP, uses an explicitly connected application, opens Keith Computer, and lets the user observe and take control. The user records a task, corrects the compiled recipe, replays it, publishes it as a skill, and invokes it from a channel.

The same release then exposes a deliberate harness defect. Keith captures the failed trace, attributes the harness cause, creates several candidates, evaluates them against search and inaccessible held-out tasks, promotes a non-regressing winner through the real self-evolution path, reruns successfully, and restores the prior harness in one action.

The release remains in progress if any named platform lacks credentialed proof, any authority boundary can be widened, any profile can cross into another, any credential leaks, any computer input can race, any recording retains a secret, any evaluator can be influenced by a candidate, any external action can be blindly replayed, or any promoted change cannot be reversed.
