<!-- GENERATED by cg specgen from spec/ kvx — DO NOT EDIT. Edit the .kvx source and regenerate. -->

# Requirements

Keith Everywhere turns the existing persistent Keith runtime into one agent that can repair defects in its own harness through evidence, meet users across major communication channels, operate as an Agent Client Protocol agent, connect safely to external applications through plugins and Composio, and drive an isolated computer that users can watch, take over, and teach through demonstration. The program reuses the existing channel gateway, MCP manager, WASI plugin host, browser runner, self-evolution pipeline, daemon, sessions, profiles, credentials, and web client. Every surface shares explicit identity, permission, approval, audit, trace, cancellation, and recovery contracts. The ten-agent execution plan is encoded as conflict-aware dependency waves and no feature counts as complete without a real integrated journey.

## Requirement 1: Shared identity, authority, approval, audit, and trace spine

**User Story:** As the owner, I want every new surface to share the same authority model, so that adding reach never creates a second uncontrolled agent runtime.

### Acceptance Criteria

1. THE platform SHALL define stable typed identifiers for external principal, profile, connected account, channel route, ACP connection, computer session, demonstration, recipe, and harness candidate.
2. EVERY external action SHALL carry profile, session, acting principal, requested capability, action risk, approval state, cancellation identity, reply route where applicable, and audit correlation.
3. THE most restrictive profile, session, connector, channel, ACP client, plugin, computer, and task policy SHALL win, and no adapter SHALL widen authority during translation.
4. CONSEQUENTIAL actions including external communication, deletion, purchase, account change, credential change, and irreversible computer input SHALL use one approval contract.
5. TRACE bundles SHALL represent model events, tool calls, observations, corrections, retries, completion decisions, costs, latency, failures, and durable state transitions without storing secrets or private reasoning.
6. CONTROL leases SHALL guarantee that at most one of Keith or the user can inject computer input, while observers remain read-only.
7. A contract suite SHALL prove serialization, version negotiation, denial on unknown capabilities, cancellation propagation, profile isolation, approval non-bypass, redaction, and exclusive control.

## Requirement 2: Durable lifecycle and truthful observability

**User Story:** As an operator, I want every connector and computer to survive ordinary failure honestly, so that broad integration remains dependable.

### Acceptance Criteria

1. CHANNEL adapters, ACP connections, plugin invocations, Composio sessions, computer sessions, recordings, recipes, and harness experiments SHALL have durable states with validated transitions.
2. RESTART SHALL reconcile committed state, expire stale leases, classify uncertain non-repeatable actions as interrupted, and never blindly replay an external side effect.
3. HEALTH projections SHALL be derived from real lifecycle state and SHALL NOT fabricate connection, screen, tool, delivery, recording, evaluation, or completion activity.
4. EVERY bounded service SHALL enforce explicit concurrency, time, retry, byte, CPU, memory, disk, and event-rate ceilings appropriate to its workload.
5. THE web and TUI SHALL expose safe error, last transition time, restartability, cancellation, and the owning profile or session.
6. A restart and fault suite SHALL prove recovery, terminal-state honesty, uncertain-action handling, lease expiry, resource reclamation, and cross-profile isolation.

## Requirement 3: Complete trace-driven harness fault diagnosis

**User Story:** As the owner, I want Keith to recognize when its operating harness caused a task failure, so that it repairs the right layer rather than blaming the model or blindly retrying.

### Acceptance Criteria

1. THE diagnostic input SHALL include complete bounded execution traces, relevant harness source, task outcome, user corrections, tool schemas, context selection, retries, completion decisions, and deterministic runtime evidence.
2. FAILURES SHALL be classified as model, environment, user-input, external service, task ambiguity, or harness caused with evidence and confidence.
3. HARNESS fault categories SHALL include context selection, tool schema, tool availability, routing, planning, retry, recovery, compaction, memory selection, permission dead end, translation loss, and termination or completion logic.
4. A proposed diagnosis SHALL name the causal harness component, reproduction, expected behavioral change, target metric, baseline, threshold, cost ceiling, and revert threshold before any edit.
5. THE diagnostic agent SHALL have no ability to alter trace evidence, evaluators, hidden corpora, approval policy, protected surfaces, or promotion records.
6. A suite SHALL prove correct attribution for representative harness and non-harness failures, duplicate suppression, injection resistance, redaction, and no diagnosis from score alone when causal evidence is absent.

## Requirement 4: Bounded candidate search and full-history inspection

**User Story:** As the operator, I want repair proposals compared rather than immediately trusted, so that self-repair is evidence-based.

### Acceptance Criteria

1. THE proposer SHALL inspect selectively retrieved prior candidate source, scores, diffs, and raw traces through a bounded read-only history view.
2. ONE experiment SHALL support multiple independently identified candidate patches, including a no-change baseline, under file, byte, dependency, token, time, and cost limits.
3. EDITABLE harness areas SHALL be explicitly allowlisted and SHALL exclude evaluator code, hidden tasks, credentials, personal-memory authority, approvals, release verification, rollback, and the self-evolution guard.
4. EACH candidate SHALL be staged in an isolated shadow tree and SHALL never modify the live harness during proposal or evaluation.
5. THE candidate registry SHALL preserve parentage, hypothesis, source digest, diff, trace references, scores, cost, latency, safety result, and terminal disposition.
6. A suite SHALL prove candidate isolation, history bounds, protected-target refusal, evaluator inaccessibility, resource ceilings, crash cleanup, and durable restart.

## Requirement 5: Independent evaluation, Pareto selection, promotion, and reversal

**User Story:** As the owner, I want a repaired harness to become real only after held-out proof, so that Keith cannot reward-hack its way into production.

### Acceptance Criteria

1. SEARCH, validation, and held-out evaluation sets SHALL be versioned and separated, and the proposer SHALL never receive held-out inputs, expected outputs, or results.
2. CANDIDATES SHALL be measured against task success, truthful completion, safety, user-correction adherence, cost, latency, retries, and resource use.
3. SELECTION SHALL retain a Pareto frontier and SHALL refuse promotion when improvement is not reproducible, statistically meaningful for the declared slice, or within all regression bounds.
4. PROMOTION SHALL use the existing real build, signed artifact, canary worker, observation window, known-good pin, and one-action reversal path.
5. ADVISORY and shadow modes SHALL be available before autonomous promotion, and the current task SHALL retry only under the promoted or explicitly approved candidate.
6. A real journey SHALL introduce a harness defect, observe the task fail, diagnose it, propose alternatives, fix the reproduction, pass held-out regression, promote the winner, rerun successfully, and restore the original harness.

## Requirement 6: Universal versioned channel adapter contract

**User Story:** As a user, I want Keith to behave consistently across communication platforms, so that channels are surfaces of one durable agent.

### Acceptance Criteria

1. THE contract SHALL cover inbound events, outbound sends, identities, conversations, threads, replies, mentions, commands, edits, deletion, reactions, attachments, voice, rich content, typing, receipts, rate limits, reconnect, cancellation, and capability discovery.
2. PLATFORM limitations SHALL be declared through capabilities and SHALL never be represented as successful unsupported behavior.
3. ADAPTER errors SHALL classify authentication, permission, malformed event, rate limit, transient network, permanent destination, unsupported feature, and uncertain acknowledgement.
4. EVERY adapter SHALL submit ordinary SessionActions through AgentConnection and SHALL NOT execute models, arbitrary tools, personal-memory reads, or alternate agent loops.
5. WEBHOOK adapters SHALL verify signatures before parsing untrusted bodies and socket or polling adapters SHALL persist bounded reconnect cursors.
6. A common conformance suite SHALL prove normalization, ordering, deduplication, media bounds, feature declarations, retries, cancellation, malformed input, restart, and isolation.

## Requirement 7: Major interactive and delivery channel coverage

**User Story:** As a user, I want Keith wherever I already communicate, so that Web, TUI, and Discord are not the only practical surfaces.

### Acceptance Criteria

1. THE supported interactive matrix SHALL include Discord, Slack, Telegram, WhatsApp Cloud, Microsoft Teams, Google Chat, and Matrix.
2. EMAIL SHALL support inbound IMAP or provider events and outbound SMTP or provider send with threading, bounded attachments, reply identity, retry classification, and explicit possible-duplicate state.
3. EACH platform SHALL implement the subset it advertises for replies, threads, mentions, commands, edits, reactions, media, voice, typing, and receipts.
4. ACCOUNT setup SHALL expose required credentials, callback or webhook state, platform scopes, connection health, reconnect state, and a safe test action.
5. GROUP routes SHALL retain explicit mention, shared-memory, participant, tool, schedule, proactive-post, and profile isolation policies.
6. A real-account matrix SHALL prove inbound, reply, attachment, restart, scheduled return, rate limiting, duplicate handling, deletion or revocation, and cross-profile isolation for every platform called supported.

## Requirement 8: Durable multi-adapter operation and account UX

**User Story:** As an operator, I want many channel accounts running together, so that expanding reach does not reduce delivery reliability.

### Acceptance Criteria

1. THE gateway SHALL supervise multiple instances of one adapter and multiple adapter kinds with independent bounded queues, health, restart, and rate limits.
2. ROUTING SHALL bind platform account, conversation, thread, sender, group policy, profile, session selection, and reply route deterministically.
3. THE outbox SHALL preserve stable delivery keys, platform receipts, attempt state, possible duplicate state, cancellation, and proactive return across restart.
4. THE web client SHALL connect, configure, test, pause, resume, inspect, and remove channel accounts without exposing raw secrets.
5. ONE failing or throttled platform SHALL NOT block another platform, interactive Web or TUI work, or daemon health.
6. A stress suite SHALL prove concurrent accounts, queue fairness, notification budgets, credential rotation, webhook replay, process restart, and isolated terminal failure.

## Requirement 9: Complete stable ACP v1 agent lifecycle

**User Story:** As an ACP client user, I want Keith to operate as a first-class Agent Client Protocol agent, so that editors and clients can use the same persistent runtime.

### Acceptance Criteria

1. KEITH SHALL implement stable ACP v1 initialization, capability negotiation, authentication metadata, session create, load, resume, fork, prompt, cancel, and terminal closure.
2. ONE ACP connection SHALL support multiple concurrent Keith sessions with independent ordering, cancellation, permissions, and durable resume.
3. PROMPTS and content blocks SHALL map losslessly where possible to Keith attachments and SessionActions, with explicit unsupported errors rather than silent loss.
4. SESSION updates SHALL stream assistant content, plan, safe thought summaries, tool state, terminal output, diffs, usage, failure, and final state from real Keith events.
5. DISCONNECT SHALL leave durable work governed by the action policy and reconnect SHALL resume without duplicate prompts or lost committed events.
6. A protocol suite SHALL prove initialization, concurrency, streaming, cancellation, resume, malformed JSON-RPC, batch handling, disconnect, restart, and version refusal.

## Requirement 10: ACP client capabilities, permissions, MCP, transports, and version boundary

**User Story:** As an ACP client operator, I want Keith to use client-provided facilities without escaping client authority, so that interoperability remains safe.

### Acceptance Criteria

1. CLIENT filesystem, terminal, permission, and MCP capabilities SHALL be represented as scoped tools and SHALL never widen the profile workspace, process, network, or credential boundary.
2. TOOL permission requests SHALL use ACP bidirectional requests while remaining subject to Keith mandatory denials and profile ceilings.
3. STDIO SHALL be the required local transport; HTTP or SSE and WebSocket SHALL be supported for managed deployment with equivalent framing, authentication, cancellation, and closure semantics.
4. MCP configuration supplied by the client SHALL remain session scoped and SHALL pass through Keith MCP policy, schema bounds, credential references, and health checks.
5. DRAFT ACP v2 SHALL be implemented behind an explicit unstable feature and runtime flag with separate handlers and no silent downgrade or schema conversion.
6. INTEROPERABILITY SHALL be proven against real ACP clients and protocol fixtures for files, terminal, MCP, permissions, concurrent sessions, cancellation, reconnect, and unsupported-version refusal.

## Requirement 11: Typed executable plugin ABI

**User Story:** As a plugin developer, I want real typed invocation rather than lifecycle-only hooks, so that extensions can safely add useful capabilities.

### Acceptance Criteria

1. THE plugin ABI SHALL carry versioned typed request and response payloads for command, tool, health, activation, migration, and deactivation.
2. PLUGIN tools and commands SHALL register name, description, input and output schema, risk, timeout, cancellation, streaming, concurrency, and required grants.
3. WASI components SHALL receive only explicit host calls for bounded HTTP, profile-local storage, named credentials, event emission, artifacts, clock, and safe logging.
4. INVOCATION SHALL enforce memory, fuel, input, output, time, process, filesystem, network, credential, and concurrent-call limits.
5. PACKAGE identity SHALL include manifest version, plugin id, version, API range, publisher, digest, signature, grants, hooks, tools, and migration contract.
6. A conformance suite SHALL prove payload exchange, schema validation, cancellation, output streaming, grant denial, resource exhaustion, crash isolation, and secret redaction using real WASI components.

## Requirement 12: Plugin lifecycle, provenance, catalog, and safe mode

**User Story:** As the owner, I want plugins to remain removable and auditable, so that extensibility cannot wedge or silently own Keith.

### Acceptance Criteria

1. LIFECYCLE SHALL support discover, inspect, install, activate, health, disable, update, migrate, rollback, uninstall, and quarantine with durable state.
2. UPDATES SHALL verify publisher continuity, compatibility, digest, signature, declared grant changes, migration result, and rollback bytes before activation.
3. NEW or widened grants SHALL require explicit human approval and SHALL NOT be inferred from plugin output or previous unrelated grants.
4. SAFE mode SHALL start Keith with all third-party plugins disabled and SHALL remain available after a corrupt package, failed migration, crash loop, or incompatible API.
5. THE web client SHALL present plugin identity, publisher, version, health, tools, grants, data access, recent calls, update diff, disable, rollback, and uninstall.
6. A hostile-package suite SHALL prove signature refusal, traversal denial, network and credential denial, migration rollback, crash quarantine, safe-mode startup, and complete uninstall.

## Requirement 13: Per-profile Composio sessions and connected-account control

**User Story:** As a user, I want Keith to connect to many applications without custom-building each API, so that external action breadth arrives quickly and remains controllable.

### Acceptance Criteria

1. EACH Keith profile SHALL map to a stable Composio user identity and SHALL maintain bounded resumable sessions without exposing provider API keys to the model or browser.
2. CONNECTED accounts SHALL expose toolkit, account identity, auth configuration, granted scopes, connection state, last health, selection precedence, and revocation.
3. THE integration SHALL use session-based hosted MCP for portable tool access and SHALL restrict toolkits and tools rather than enabling the full catalog by default.
4. TOOL discovery SHALL remain within context and schema budgets and SHALL preserve exact account selection when several accounts exist for one toolkit.
5. KEITH SHALL apply its own risk, approval, audit, cancellation, timeout, and result-redaction policy before and after every Composio MCP call.
6. A real-account suite SHALL prove connect, resume, discover, read, approval-gated write, multiple-account selection, expiry recovery, revocation, deletion, and cross-profile isolation.

## Requirement 14: Isolated durable Keith Computer

**User Story:** As a user, I want Keith to have a real computer I can see, so that it can complete visual workflows beyond APIs and semantic fetches.

### Acceptance Criteria

1. A computer session SHALL run in an isolated Linux workstation with a headed browser, dedicated profile, bounded filesystem, clipboard, process tree, network, CPU, memory, disk, and lifetime.
2. COMPUTERS SHALL support create, start, suspend, resume, snapshot, restore, reset, terminate, idle reclaim, and profile deletion with durable state and safe errors.
3. PERSISTENT and ephemeral modes SHALL be explicit, and profile or credential state SHALL never cross computer ownership boundaries.
4. SCREEN access SHALL use an authenticated short-lived stream and SHALL reveal no backend VNC, browser-debug, bearer, or credential endpoint to an unauthorized viewer.
5. CREDENTIAL injection SHALL use named grants and SHALL avoid exposing reusable secrets to model context, recordings, screenshots, clipboard history, URLs, logs, or recipes.
6. A process suite SHALL prove lifecycle, stream authorization, isolation, snapshot restore, reset, idle reclaim, resource ceilings, crash recovery, and complete deletion.

## Requirement 15: Multimodal perception, computer action, verification, and recovery

**User Story:** As a user, I want Keith to drive its computer reliably, so that it acts from observed state rather than blind coordinates.

### Acceptance Criteria

1. OBSERVATIONS SHALL combine current screenshot, browser DOM, accessibility tree, focused window, URL, viewport, cursor, recent actions, downloads, dialogs, and safe application metadata when available.
2. ACTIONS SHALL include move, click, double click, drag, scroll, key, text, shortcut, clipboard, file upload or download, tab, window, navigation, and wait with bounded inputs.
3. SEMANTIC targets SHALL be preferred over coordinates; coordinate actions SHALL include the source frame identity and SHALL be refused against stale geometry.
4. EVERY meaningful action SHALL produce a new observation and progress check before continuation, with bounded retry and alternate-strategy recovery.
5. CONSEQUENTIAL visual actions SHALL pass through the shared approval contract immediately before execution and SHALL invalidate approval when the target changes.
6. A task corpus SHALL measure completion, action count, latency, stale-target recovery, popup and layout handling, download and upload behavior, cancellation, and unsafe-action refusal.

## Requirement 16: Live screen, exclusive co-control, and immediate takeover

**User Story:** As a user, I want to watch and take over Keith's computer, so that automation remains understandable and interruptible.

### Acceptance Criteria

1. THE web app SHALL render the live computer screen with current owner, connection quality, active action, intended next action, recording state, and safe error.
2. CONTROL states SHALL be KeithControl, UserControl, and Paused, with one durable exclusive lease and read-only observers.
3. USER takeover SHALL immediately cancel queued and in-flight Keith input, acquire the lease, and prevent new Keith input until control is returned.
4. KEITH SHALL request control rather than stealing it and SHALL stop on stream desynchronization, stale lease, focus ambiguity, or user activity.
5. CLIPBOARD, file transfer, full screen, scaling, keyboard, touch, and reconnect SHALL remain profile scoped and accessible.
6. A live journey SHALL prove concurrent observation, user takeover during a multi-step action, cancellation, manual work, return to Keith, reconnect, and no simultaneous input.

## Requirement 17: Teach by demonstration and editable TaskRecipes

**User Story:** As a user, I want to demonstrate a task in Keith's computer and have Keith learn it, so that automation can be taught inside the product.

### Acceptance Criteria

1. A demonstration SHALL synchronously capture screen frames, raw pointer and keyboard events, DOM and accessibility targets, URL, window, application, clipboard and file operations, timing, control owner, pauses, and optional narration.
2. RECORDING SHALL detect secrets and sensitive fields, redact captured values, and replace them with named credential or runtime parameters before persistence.
3. THE compiler SHALL produce a versioned editable TaskRecipe with inputs, preconditions, semantic steps, visual fallbacks, expected observations, checkpoints, approvals, recovery branches, and completion conditions.
4. THE user SHALL be able to label parameters, remove steps, correct targets, add confirmations, replay from a checkpoint, compare results, and discard or publish the recipe.
5. A recipe SHALL replay first in a shadow or explicit test context and SHALL not become a reusable skill until its declared checks pass and the user accepts the readable procedure.
6. A suite SHALL prove synchronized capture, secret redaction, semantic compilation, changed-layout recovery, user correction, checkpoint replay, versioning, rollback, and deletion of recording media and derived recipes.

## Requirement 18: Integrated Web, TUI, and API surfaces

**User Story:** As a user, I want these capabilities presented as one Keith rather than separate dashboards, so that control stays understandable.

### Acceptance Criteria

1. THE existing Keith Computer work stage SHALL become the live screen surface while retaining truthful tool, goal, child, wait, terminal, and final-state projections.
2. THE web app SHALL provide Channels, Apps, Plugins, ACP connections, Computers, Recordings, Recipes, and Harness Repairs without duplicating daemon business logic.
3. EVERY mutation SHALL be authenticated, exact-origin and CSRF protected where applicable, profile scoped, approval aware, idempotent where possible, and audited.
4. THE TUI and protocol SHALL expose lifecycle, health, cancellation, control, connection, recipe, candidate, promotion, rollback, and safe-error operations needed without the web client.
5. UI labels SHALL be ordinary language, responsive, keyboard complete, screen-reader labeled, reduced-motion safe, and truthful about unsupported or unqualified platforms.
6. A browser and protocol suite SHALL prove navigation, connection, live updates, cancellation, takeover, recording, app approval, harness review, restart, responsive layout, and cross-profile isolation.

## Requirement 19: Cross-surface security, privacy, data control, and failure containment

**User Story:** As the owner, I want integrations to compose without composing their authority, so that one compromised surface cannot pivot through another.

### Acceptance Criteria

1. CHANNEL content, ACP clients, plugins, Composio tools, websites, computer applications, recordings, recipes, traces, and candidate patches SHALL be treated as mutually untrusted inputs.
2. AN input from one surface SHALL NOT enable self-evolution, install a plugin, connect an account, widen a grant, take computer control, approve an action, expose a credential, or select another profile.
3. EXPORT and deletion SHALL cover channel accounts and events, ACP metadata, plugins, connected accounts, computer state, recordings, recipes, traces, candidates, and derived indexes with exact remnant reporting.
4. AUDIT records SHALL correlate cross-surface actions without storing secrets, full private content, reusable stream URLs, raw credentials, or private reasoning.
5. ONE crashed, compromised, throttled, corrupt, or disconnected surface SHALL be quarantined without preventing daemon startup, ordinary conversation, cancellation, reversal, or data deletion.
6. AN adversarial suite SHALL cover injection, SSRF, webhook forgery, protocol confusion, plugin escape, OAuth substitution, stream hijack, stale input, recording leakage, evaluator tampering, cross-profile access, and crash at every durable boundary.

## Requirement 20: Integrated product journey and release truth

**User Story:** As the owner, I want one real proof that all five systems work together, so that parallel implementation does not produce disconnected demos.

### Acceptance Criteria

1. A real user SHALL message Keith through a non-Discord channel, continue the same durable session through Web or ACP, invoke a connected application, and observe or take over Keith Computer.
2. THE user SHALL record a computer task, compile and correct a TaskRecipe, replay it successfully, publish it as a skill, and invoke it from a channel.
3. THE journey SHALL expose a harness-caused failure, execute bounded candidate search and held-out evaluation, promote a repair, rerun successfully, and reverse the repair.
4. THE release gate SHALL run formatting, strict linting, focused crates, protocol fixtures, real process suites, browser journeys, security gate, platform gate, restart recovery, and Codify trace evidence.
5. A platform, application, transport, recipe, computer mode, or harness autonomy level SHALL be called supported only when its real credentialed or process-backed journey passed; unavailable external approval SHALL remain explicit.
6. THE feature SHALL remain in progress until every requirement is traced to code, qualification, evidence, and a published commit with no known authority-widening, data-loss, unrecoverable, or fabricated-success issue.

