name: ci

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.93.0
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo ci
      - run: cargo clean-checkout

  supply-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.93.0
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny,cargo-audit
      - run: cargo deny check
      - run: cargo audit

